$base = <<BASE
sudo apt-get install -q -y wget unzip ca-certificates
sudo curl -s -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 > /usr/local/bin/jq
sudo chmod +x /usr/local/bin/jq
BASE

$vault_install = <<VAULT_INST
#VAULT=0.8.3
#VAULT_ZIP=/vagrant/bin/vault_${VAULT}_linux_amd64.zip
#if [ ! -f $VAULT_ZIP ]; then
#  mkdir -p /vagrant/bin
#  wget https://releases.hashicorp.com/vault/${VAULT}/vault_${VAULT}_linux_amd64.zip --quiet -O $VAULT_ZIP
#fi
cp /vagrant/vault /tmp/vault
cd /tmp
#unzip -q $VAULT_ZIP >/dev/null
sudo chmod +x vault
sudo mv vault /usr/local/bin
sudo chmod 0755 /usr/local/bin/vault
sudo chown root:root /usr/local/bin/vault
VAULT_INST

$vault_env = <<VAULT_ENV
sudo cat << EOF > /etc/profile.d/vault.sh
export VAULT_ADDR="http://192.168.50.101:8200"
export VAULT_SKIP_VERIFY=true
EOF
VAULT_ENV

$vault_run = <<VAULT_RUN
nohup /usr/local/bin/vault server -dev \
  -dev-root-token-id="password" \
  -dev-listen-address="0.0.0.0:8200" 0<&- &>/dev/null &
VAULT_RUN

$vault_policies = <<VAULT_POLICIES
vault auth password
vault policy-write saltstack/minion/springboot /vagrant/springboot.acl
vault auth-enable approle
vault write auth/approle/role/springboot secret_id_ttl=1m secret_id_num_uses=1 period=10m policies=saltstack/minion/springboot bound_cidr_list=192.168.50.102/32
vault write auth/approle/role/springboot/role-id role_id=80db5038-2bf9-2fda-2367-e7ecc81f3dcd
vault write secret/vault-si-boot password=hellovault
VAULT_POLICIES

$hosts_file = <<HOSTS_FILE
sudo cat << EOF >> /etc/hosts
192.168.50.100  saltmaster saltmaster.example.com
192.168.50.101  vault vault.example.com
192.168.50.102  springboot springboot.example.com
EOF
HOSTS_FILE

$saltmaster = <<SALTMASTER
curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sudo sh bootstrap-salt.sh -M -N git 2017.7.2
SALTMASTER

$saltminion = <<SALTMINION
curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sudo sh bootstrap-salt.sh -A 192.168.50.100 git 2017.7.2
SALTMINION

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    vb.customize ["modifyvm", :id, "--chipset", "ich9"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  config.vm.define "saltmaster" do |vault|
    vault.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
    vault.vm.network :private_network, ip: "192.168.50.100"
    vault.vm.box = "bento/ubuntu-16.04"
    vault.vm.hostname = "saltmaster"
    vault.vm.synced_folder "saltstack/salt/", "/srv/salt"
    vault.vm.synced_folder "saltstack/pillar/", "/srv/pillar"
    vault.vm.synced_folder "saltstack/etc/", "/etc/salt"
    vault.vm.provision "shell", inline: $base
    vault.vm.provision "shell", inline: $hosts_file
    vault.vm.provision "shell", inline: $saltmaster
    vault.vm.provision "shell", inline: 'service salt-master restart',run: 'always'
  end
  config.vm.define "vault" do |vault|
    vault.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    vault.vm.network :private_network, ip: "192.168.50.101"
    vault.vm.network "forwarded_port", guest: 8200, host: 8200
    vault.vm.box = "bento/ubuntu-16.04"
    vault.vm.hostname = "vault"
    vault.vm.provision "shell", inline: $base
    vault.vm.provision "shell", inline: $vault_install
    vault.vm.provision "shell", inline: $vault_env
    vault.vm.provision "shell", inline: $vault_run, run: 'always'
    vault.vm.provision "shell", inline: $vault_policies, run: 'always'
    vault.vm.provision "shell", inline: $hosts_file
    vault.vm.provision "shell", inline: $saltminion
  end
  config.vm.define "springboot" do |springboot|
    springboot.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    springboot.vm.network :private_network, ip: "192.168.50.102"
    springboot.vm.network "forwarded_port", guest: 8080, host: 8080
    springboot.vm.box = "lanceplarsen/bento-ubuntu-1604-springboot"
    springboot.vm.hostname = "springboot"
    springboot.vm.provision "shell", inline: $base
    springboot.vm.provision "shell", inline: $hosts_file
    springboot.vm.provision "shell", inline: $saltminion
  end
end
